name: ReaPack index update

on:
  push:
    branches: [main]
    paths:
      - '**.lua'
      - index.xml

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

     # - name: Install reapack-index
       # run: gem install reapack-index

      - name: Run reapack-index
        run: reapack-index .

      - name: Commit and push updated index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.xml index.xml.gz index.yaml || true
          git commit -m "Update ReaPack index" || true
          git push
